options:
    machineType: 'N1_HIGHCPU_8'
steps:
  - name: 'gcr.io/$PROJECT_ID/scala-sbt'
    args: ['clean', 'test', 'docker:publishLocal']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'google-cloud-build-mqtt-webhooks:1.0', 'eu.gcr.io/$PROJECT_ID/google-cloud-build-mqtt-webhooks:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/$PROJECT_ID/google-cloud-build-mqtt-webhooks:$COMMIT_SHA']
