steps:
  - name: 'gcr.io/$PROJECT_ID/scala-sbt'
    args: ['clean', 'test', 'docker:publishLocal']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'google-cloud-builder:0.1.0-SNAPSHOT', 'eu.gcr.io/$PROJECT_ID/google-cloud-builder:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/$PROJECT_ID/google-cloud-builder:$COMMIT_SHA']